version: '3'
services:
  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - '7279:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass w8vfpGTA2KPvvfMbFEnt6
    volumes:
      - "./dev-data/redis-data:/data"

  flower:
    image: mher/flower:0.9.7
    restart: always
    command: flower --port=5555
    environment:
      CELERY_BROKER_URL: redis://:w8vfpGTA2KPvvfMbFEnt6@redis:7279/0
    ports:
      - "50555:5555"

  smtp:
    image: maildev/maildev:2.0.2
    ports:
      - 1080:1080
      - 1025:1025