version: '3'
services:
  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass w8vfpGTA2KPvvfMbFEnt6
    volumes:
      - "./dev-data/redis-data:/data"

  flower:
    image: mher/flower:0.9.7
    restart: always
    command: flower --port=5555
    environment:
      CELERY_BROKER_URL: redis://:w8vfpGTA2KPvvfMbFEnt6@redis:6379/0
    ports:
      - "49555:5555"