# Generated by Django 4.0.4 on 2022-05-27 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hidl_vpn", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DummyDevice",
            fields=[
                (
                    "device_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hidl_vpn.device",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("hidl_vpn.device",),
        ),
        migrations.CreateModel(
            name="DummyVpnServer",
            fields=[
                (
                    "vpnserver_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hidl_vpn.vpnserver",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dummy Server",
            },
            bases=("hidl_vpn.vpnserver",),
        ),
    ]
