# Generated by Django 4.0.4 on 2022-05-14 13:01

#    Hidl Route - opensource vpn management system
#    Copyright (C) 2023 Dmitry Berezovsky, Alexander Cherednichenko
#
#    Hidl Route is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Hidl Route is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hidl_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WireguardServer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("private_key", models.CharField(max_length=1024)),
                ("server", models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to="hidl_core.server")),
            ],
        ),
        migrations.CreateModel(
            name="WireguardPeer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_key", models.CharField(max_length=1024)),
                ("device", models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="hidl_core.device")),
            ],
        ),
    ]
