# Generated by Django 4.0.4 on 2022-05-19 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hidl_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenVPNServer",
            fields=[
                (
                    "server_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hidl_core.server",
                    ),
                ),
                ("cert_storage_dir", models.CharField(blank=True, max_length=1024)),
                ("extra_config", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "OpenVPN Server",
            },
            bases=("hidl_core.server",),
        ),
    ]
