name: Backmerge
on:
  push:
    # Branches to be back-merged into master
    branches:
      - beta
      - prod

jobs:
  run:
    name: Backmerge into development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: '${{ github.ref }}'

      - name: Merge into master
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: '${{ github.ref }}'
          target_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}