name: Build docker image
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      git_ref:
        required: true
        type: string
      git_ref_name:
        required: true
        type: string
        default: "${{ github.ref_name }}"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: hidlroute/server
  GIT_REF: "${{ ((inputs.git_ref) && inputs.git_ref) || github.ref }}"
  GIT_REF_NAME: "${{ ((inputs.git_ref_name) && inputs.git_ref_name) || github.ref_name }}"

jobs:
  run:
    name: Build and publish docker images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      DOCKER_VERSION_SUFFIX: "${{ ((env.GIT_REF_NAME == 'beta') && '-beta') || ((env.GIT_REF_NAME == 'master') && '-dev') || '' }}"
      DOCKER_VERSION_ALIAS: "${{ ((env.GIT_REF_NAME == 'beta') && 'beta') || ((env.GIT_REF_NAME == 'master') && 'dev') || 'latest' }}"
      DOCKER_CHANNEL: "${{ ((env.GIT_REF_NAME == 'beta') && 'beta') || ((env.GIT_REF_NAME == 'master') && 'dev') || 'stable' }}"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: "${{ env.GIT_REF }}"

      - name: Evaluate build args
        run: |
          VERSION=`make get-version`
          echo "Version = $VERSION"
          export RELEASE_DATE=`TZ="Europe/Kiev" date +%Y-%m-%d`
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "RELEASE_DATE=$RELEASE_DATE" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
            RELEASE_DATE=${{ env.RELEASE_DATE }}
            CHANNEL=${{ env.DOCKER_CHANNEL }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_VERSION_ALIAS }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}${{ env.DOCKER_VERSION_SUFFIX }}
