name: Build template
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      git_ref:
        required: true
        type: string
jobs:
  run:
    name: Build template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: "${{ ((inputs.git_ref) && inputs.git_ref) || github.ref }}"

      - name: Make template archive
        run: make template NO_VENV=True

      - uses: actions/upload-artifact@v3
        with:
          name: hidlroute-template
          path: dist/template/hidlroute-template.zip