name: Build wheel
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      git_ref:
        required: true
        type: string
    secrets:
      pypi_password:
        required: true

jobs:
  run:
    name: Build python packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: "${{ ((inputs.git_ref) && inputs.git_ref) || github.ref }}"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements-dev.txt

      - name: Run build
        run: make build NO_VENV=True

      - name: Publish packages
        run: make publish NO_VENV=True PYPI_API_KEY=${{ secrets.pypi_password }}

      - uses: actions/upload-artifact@v3
        with:
          name: hidlroute-server-packages
          path: dist/*.