name: Build docker image
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: hidlroute/server

jobs:
  run:
    name: Build and publish docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
#          ref: 'refs/tags/v${{ env.VERSION }}'

      - name: Evaluate build args
        run: |
          VERSION=`make get-version`
          echo "Version = $VERSION"
          export RELEASE_DATE=`TZ="Europe/Kiev" date +%Y-%m-%d`
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "RELEASE_DATE=$RELEASE_DATE" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
            RELEASE_DATE=${{ env.RELEASE_DATE }}
            CHANNEL=${{ ((github.ref_name == 'beta') && 'beta') || ((github.ref_name == 'master') && 'dev') || 'stable' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ ((github.ref_name == 'beta') && 'beta') || ((github.ref_name == 'master') && 'dev') || 'latest' }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}${{ ((github.ref_name == 'beta') && '-beta') || ((github.ref_name == 'master') && '-dev') || '' }}
