name: Generate changelog
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      git_ref:
        required: true
        type: string

jobs:
  run:
    name: Update Unreleased Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: "${{ ((inputs.git_ref) && inputs.git_ref) || github.ref }}"

      - name: Changelog
        id: generate_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          toTag: ${{ github.ref }}

      - name: Persist changelog
        run: |
          cat <<EOF > changelog.md
          ${{ steps.generate_changelog.outputs.changelog }}
          EOF
          echo "::group::Changelog";
          cat changelog.md;
          echo "::endgroup::";

      - uses: actions/upload-artifact@v3
        with:
          name: changelog
          path: changelog.md