name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to be assigned for this release'
        required: true

jobs:
  sanity-check:
    name: Run sanity check
    uses: ./.github/workflows/sanity-check.yml
    with:
      git_ref: '${{ github.ref }}'

  changelog:
    name: Generate changelog
    uses: ./.github/workflows/generate-change-log.yml
    with:
      git_ref: '${{ github.ref }}'

  build-template:
    name: Generate bootstrap template
    uses: ./.github/workflows/build-template.yml
    with:
      git_ref: '${{ github.ref }}'

  prepare-release:
    name: Prepare release
    needs: [ sanity-check, changelog, build-template ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: '${{ github.ref }}'

      - name: Set new version
        run: |
          make set-version VERSION="${{ github.event.inputs.version }}"

      - name: Download changelog
        uses: actions/download-artifact@v3
        with:
          name: changelog

      - name: Download bootstrap template
        uses: actions/download-artifact@v3
        with:
          name: hidlroute-template

      - name: Read changelog
        id: changelog
        run: echo "::set-output name=changelog::$(cat changelog.md)"

      - name: Commit bumped version
        uses: EndBug/add-and-commit@v5
        with:
          author_name: Github Bot
          author_email: github@bot.com
          message: "Version bump and changelog update. New version is ${{ github.event.inputs.version }}"
          add: "./src/hidlroute/__version__.py"
          push: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge master -> prod
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: '${{ github.ref }}'
          target_branch: prod
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Github Release
        id: create_release
        uses: actions/create-release@v1.10.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v${{ github.event.inputs.version }}'
          release_name: 'Version ${{ github.event.inputs.version }}'
          body: |
            ${{ steps.changelog.outputs.changelog }}
          artifacts: hidlroute-template
          draft: false
          prerelease: true

  build-docker:
    name: Release docker image
    needs: [ prepare-release ]
    uses: ./.github/workflows/build-docker.yml
    permissions:
      contents: read
      packages: write
    with:
      git_ref: 'refs/tags/v${{ github.event.inputs.version }}'
      git_ref_name: '${{ github.event.inputs.version }}'

  build-wheel:
    name: Release python package
    needs: [ prepare-release ]
    uses: ./.github/workflows/build-wheel.yml
    with:
      git_ref: 'refs/tags/v${{ github.event.inputs.version }}'
    secrets:
      pypi_password: '${{ secrets.pypi_password }}'