name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to be assigned for this release'
        required: true

env:
  target_tag: 'v${{ github.event.inputs.version }}'

jobs:
  sanity-check:
    name: Run sanity check
    uses: ./.github/workflows/sanity-check.yml
    with:
      git_ref: '${{ github.ref }}'

  changelog:
    name: Generate changelog
    uses: ./.github/workflows/generate-change-log.yml
    with:
      git_ref: '${{ github.ref }}'

  prepare-release:
    name: Prepare release
    needs: [ sanity-check, changelog ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: '${{ github.ref }}'

      - name: Set new version
        run: |
          make set-version VERSION="${{ github.event.inputs.version }}"

      - name: Download changelog
        uses: actions/download-artifact@v3
        with:
          name: changelog

      - name: Read changelog
        id: changelog
        run: echo "::set-output name=changelog::$(cat changelog.md)"

      - name: Commit bumped version
        uses: EndBug/add-and-commit@v5
        with:
          author_name: Github Bot
          author_email: github@bot.com
          message: "Version bump and changelog update. New version is ${{ github.event.inputs.version }}"
          add: "./src/hidlroute/__version__.py"
          push: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge master -> prod
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: '${{ github.ref }}'
          target_branch: prod
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Github Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '${{ env.target_tag }}'
          release_name: 'Version ${{ github.event.inputs.version }}'
          body: |
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: true