name: Sanity Check
on:
  push:
  workflow_call:
    inputs:
      git_ref:
        required: true
        type: string

jobs:
  run:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: "${{ ((inputs.git_ref) && inputs.git_ref) || github.ref }}"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements-dev.txt

      - name: Lint with flake8
        run: make lint NO_VENV=True

      - name: Run build to make sure it works
        run: make build NO_VENV=True